export type Locale = 'en' | 'fa' | 'ar';
export const team = [
  {
    id: 'zahra',
    initials: 'ZA',
    photo: '/team/zahra.jpg',
    name: 'Zahra Arafati',
    fa: 'زهرا عرفاتی',
    role: 'Product Designer',
    focus: 'Product thinking · UX & UI',
    skills: ['Figma', 'Design systems', 'UX research', 'Prototyping', 'Illustration'],
    experience: 'Doctoreto · MAHAK · Denxa',
    link: 'https://www.linkedin.com/in/zahraarafati',
  },
  {
    id: 'parham',
    initials: 'PH',
    photo: '/team/parham.jpg',
    name: 'Parham Hatanian',
    fa: 'پرهام حتانیان',
    role: 'Mobile Engineer',
    focus: 'Flutter · Native integrations',
    skills: ['Flutter', 'Dart', 'Swift', 'Kotlin', 'BLoC', 'Digital signing'],
    experience: 'IPAAM / ToBank · Monoppy · Carbon OS',
    link: 'https://www.linkedin.com/in/parham-hatanian',
  },
  {
    id: 'amin',
    initials: 'AA',
    photo: '/team/amin.jpg',
    name: 'Amin Azarpey',
    fa: 'امین آذرپی',
    role: 'Team Lead · Software Engineer',
    focus: 'Web · Software architecture',
    skills: ['Angular', 'Next.js', 'TypeScript', 'NestJS', 'Nx', 'Design systems'],
    experience: 'FAM · ISC · IPAAM · PGPIC',
    link: 'https://www.linkedin.com/in/amin-azarpey',
  },
  {
    id: 'erfan',
    initials: 'EE',
    photo: '/team/erfan.jpg',
    name: 'Erfan Ehsany',
    fa: 'عرفان احسانی',
    role: 'Software Engineer',
    focus: 'Backend · AI & automation',
    skills: ['Python', 'Go', 'Java', 'Spring Boot', 'Kafka', 'AI agents'],
    experience: 'FAM · ISC · Sanaap · IPAAM',
    link: 'https://www.linkedin.com/in/theerfanehsany',
  },
  {
    id: 'ali',
    initials: 'AB',
    photo: '/team/ali.jpg',
    name: 'Ali Baratloo',
    fa: 'علی براتلو',
    role: 'Site Reliability Engineer',
    focus: 'Infrastructure · Reliability',
    skills: ['Kubernetes', 'Docker', 'Linux', 'CI/CD', 'Prometheus', 'Test automation'],
    experience: 'Snapp! · Mahsan',
    link: null,
  },
];

export const stacks = [
  {
    id: 'design',
    title: ['Product & design', 'محصول و طراحی', 'المنتج والتصميم'],
    people: ['zahra'],
    items: [
      'Figma',
      'Design systems',
      'User research',
      'Prototyping',
      'UX writing',
      'Illustrator',
      'Photoshop',
      'After Effects',
      'Hotjar',
      'Clarity',
    ],
  },
  {
    id: 'web',
    title: ['Web engineering', 'مهندسی وب', 'هندسة الويب'],
    people: ['amin'],
    items: [
      'Angular',
      'React',
      'Next.js',
      'TypeScript',
      'JavaScript',
      'HTML / CSS',
      'NgRx',
      'Tailwind CSS',
      'Lit',
      'Web Components',
      'Storybook',
      'Nx',
      'Capacitor',
      'NestJS',
    ],
  },
  {
    id: 'mobile',
    title: ['Mobile experiences', 'تجربه موبایل', 'تطبيقات الجوال'],
    people: ['parham'],
    items: [
      'Flutter',
      'Dart',
      'Swift',
      'Kotlin',
      'BLoC / Cubit',
      'GetX',
      'GetIt',
      'Dio',
      'Firebase',
      'Codemagic',
      'Platform channels',
      'PKI / eKYC',
    ],
  },
  {
    id: 'backend',
    title: ['Backend & AI', 'بک‌اند و هوش مصنوعی', 'الأنظمة والذكاء الاصطناعي'],
    people: ['erfan', 'amin'],
    items: [
      'Python',
      'Go',
      'Java',
      'Spring Boot',
      'Django',
      'FastAPI',
      'Flask',
      'Gin',
      'Fiber',
      'PostgreSQL',
      'Oracle',
      'MongoDB',
      'Redis',
      'Kafka',
      'RabbitMQ',
      'Temporal',
      'Keycloak',
      'APISIX',
      'AI agents',
      'Qwen',
    ],
  },
  {
    id: 'infra',
    title: ['Infrastructure & quality', 'زیرساخت و کیفیت', 'البنية التحتية والجودة'],
    people: ['ali', 'erfan', 'amin'],
    items: [
      'Linux',
      'Docker',
      'Kubernetes',
      'Helm',
      'Terraform',
      'Ansible',
      'GitLab CI',
      'GitHub Actions',
      'Jenkins',
      'Argo CD',
      'Prometheus',
      'Grafana',
      'Zabbix',
      'OpenTelemetry',
      'Jaeger',
      'Sentry',
      'Elastic APM',
      'Jest',
      'Vitest',
      'Cypress',
    ],
  },
];

export const companies = [
  {
    id: 'pgpic',
    name: 'PGPIC',
    fa: 'پتروشیمی خلیج فارس',
    logo: '/logos/pgpic.png',
    people: 'Amin Azarpey',
    context: ['Freelance web engineering', 'مهندسی وب؛ همکاری فریلنس', 'هندسة الويب؛ عمل مستقل'],
  },
  {
    id: 'snapp',
    name: 'Snapp!',
    fa: 'اسنپ',
    logo: '/logos/snapp.svg',
    people: 'Ali Baratloo',
    context: ['Site reliability engineering', 'مهندسی قابلیت اطمینان', 'هندسة موثوقية الأنظمة'],
  },
  {
    id: 'isc',
    name: 'ISC / Central Bank Of Iran',
    fa: 'خدمات انفورماتیک / بانک مرکزی',
    logo: '/logos/cbi.svg',
    people: 'Amin Azarpey · Erfan Ehsany',
    context: [
      'Software engineering · Core banking',
      'مهندسی نرم‌افزار؛ بانکداری متمرکز',
      'هندسة البرمجيات؛ الأنظمة المصرفية',
    ],
  },
  {
    id: 'tourism-bank',
    name: 'IPAAM / Gardeshgari Bank',
    fa: 'ایپام / بانک گردشگری',
    logo: '/logos/tourism-bank.svg',
    people: 'Amin · Parham · Erfan',
    context: ['Through IPAAM / ToBank', 'از مسیر ایپام و توبانک', 'عبر IPAAM و ToBank'],
  },
  {
    id: 'melal-bank',
    name: 'FAM / Melal Bank',
    fa: 'فام / بانک ملل',
    logo: '/logos/melal-bank.png',
    people: 'Amin Azarpey · Erfan Ehsany',
    context: ['Banking products through FAM', 'محصولات بانکی از مسیر فام', 'منتجات مصرفية عبر FAM'],
  },
  {
    id: 'mahak',
    name: 'MAHAK',
    fa: 'محک',
    logo: '/logos/mahak.svg',
    people: 'Zahra Arafati',
    context: [
      'Product design · Design systems',
      'طراحی محصول و دیزاین سیستم',
      'تصميم المنتج وأنظمة التصميم',
    ],
  },
  {
    id: 'doctoreto',
    name: 'Doctoreto',
    fa: 'دکترتو',
    logo: '/logos/doctoreto.png',
    people: 'Zahra Arafati',
    context: ['Healthcare product design', 'طراحی محصول سلامت', 'تصميم المنتجات الصحية'],
  },
  {
    id: 'mahsan',
    name: 'Mahsan',
    fa: 'مهسان',
    logo: null,
    people: 'Ali Baratloo',
    context: ['DevOps · Test automation', 'دواپس و اتوماسیون تست', 'DevOps وأتمتة الاختبارات'],
  },
  {
    id: 'monoppy',
    name: 'Monoppy',
    fa: 'مونوپی',
    logo: '/logos/monoppy.png',
    people: 'Parham Hatanian',
    context: [
      'Flutter product development',
      'توسعه محصول با فلاتر',
      'تطوير المنتج باستخدام Flutter',
    ],
  },
];

export const copy = {
  en: {
    brand: 'danvar',
    descriptor: 'Product design & software engineering',
    chapters: ['Hello', 'Our people', 'Experience', 'Our tools', 'Your idea'],
    settings: 'Make yourself at home',
    settingsHint: 'A little more you. Your preferences stay in this browser.',
    close: 'Close',
    theme: 'Appearance',
    modes: ['System', 'Light', 'Dark'],
    palette: 'A change of mood',
    paletteNames: ['Almond', 'Rose', 'Clay', 'Sand', 'Sage', 'Mist'],
    keep: 'Keep this look',
    vary: 'A fresh look next visit',
    reduced: 'Less movement',
    audio: 'Read this chapter aloud',
    audioMissing: 'A voice for this language is not available on this device.',
    language: 'Language',
    hello: 'HI THERE. WE’RE DANVAR.',
    title: ['Good ideas.', 'Great company.'],
    intro:
      'We’re five specialists who care about what you’re building. From the first “what if” to the day it goes live.',
    meet: 'Get to know us',
    explore: 'Explore our experience',
    small: 'Product people. Engineering minds. Human conversations.',
    note: 'A little thought. A lot of craft.',
    paper: ['Understand the idea', 'Make it feel right', 'Build it to last'],
    paperLabel: 'HOW WE MAKE THINGS',
    paperFooter: 'One thoughtful step at a time.',
    teamLabel: 'THE PEOPLE BEHIND THE PRODUCT',
    teamTitle: ['Five perspectives.', 'One shared purpose.'],
    teamIntro:
      'Design, software and infrastructure, at the same table. Meet the people you’ll work with.',
    profile: 'Meet',
    skills: 'Selected strengths',
    linkedin: 'Professional profile ↗',
    expLabel: 'EXPERIENCE WE BRING WITH US',
    expTitle: ['Real work.', 'Real responsibility.'],
    expIntro:
      'Our people have contributed to products and teams across banking, industry, healthcare and everyday life.',
    expNote:
      'Previous employment and project experience of individual members. Select a company to see the connection.',
    source: 'Member experience',
    stackLabel: 'THE RIGHT TOOLS FOR THE WORK',
    stackTitle: ['A broad toolkit.', 'A considered choice.'],
    stackIntro:
      'Technology follows the problem. Here’s what we’ve worked with across our individual careers.',
    people: 'Experience on the team',
    contactLabel: 'EVERY GOOD PRODUCT STARTS SOMEWHERE',
    contactTitle: ['What’s on', 'your mind?'],
    contactIntro:
      'A new idea, an existing product, or a challenge you’re still figuring out. Start wherever you are.',
    needs: ['A new product', 'A better experience', 'Reliable infrastructure', 'AI & automation'],
    placeholder: 'A few words about what you want to build…',
    download: 'Save my project brief',
    downloaded: 'Your brief is saved. Nothing has been sent.',
    contactNote: 'Save a brief locally, or reach us directly by email — we read every message.',
    emailUs: 'Email us',
    pause: 'Pause story',
    play: 'Play story',
    prev: 'Previous chapter',
    next: 'Next chapter',
    skip: 'Skip to your idea',
    replay: 'Watch again',
    footer: 'Thoughtfully made, together.',
    preview: 'DESIGN PREVIEW',
    choose: 'Open preferences',
    chaptersLabel: 'Story chapters',
  },
  fa: {
    brand: 'دانور',
    descriptor: 'طراحی محصول و مهندسی نرم‌افزار',
    chapters: ['سلام', 'آدم‌های تیم', 'تجربه‌ها', 'ابزارهای ما', 'ایده تو'],
    settings: 'اینجا راحت باش',
    settingsHint: 'کمی بیشتر شبیه سلیقه تو. تنظیمات در همین مرورگر می‌ماند.',
    close: 'بستن',
    theme: 'ظاهر',
    modes: ['سیستم', 'روشن', 'تیره'],
    palette: 'یک حال‌وهوای تازه',
    paletteNames: ['بادامی', 'رز خاکی', 'سفالی', 'شنی', 'مریم‌گلی', 'آبی مه‌آلود'],
    keep: 'همین ظاهر را نگه دار',
    vary: 'ورود بعدی، حال‌وهوای تازه',
    reduced: 'حرکت کمتر',
    audio: 'این بخش را برایم بخوان',
    audioMissing: 'صدای مناسب این زبان روی دستگاه موجود نیست.',
    language: 'زبان',
    hello: 'سلام، ما دانوریم.',
    title: ['ایده‌های خوب،', 'همراه‌های خوب.'],
    intro:
      'ما پنج نفریم و به چیزی که می‌سازی اهمیت می‌دیم؛ از اولین «چی می‌شه اگه…» تا روزی که محصولت راه می‌افته.',
    meet: 'با ما آشنا شو',
    explore: 'تجربه‌هامون رو ببین',
    small: 'نگاه محصولی. ذهن مهندسی. گفت‌وگوی انسانی.',
    note: 'فکر سنجیده، ساختن با حوصله.',
    paper: ['ایده را بفهمیم', 'تجربه را طراحی کنیم', 'قابل‌اعتماد بسازیم'],
    paperLabel: 'چطور با هم می‌سازیم',
    paperFooter: 'هر قدم، با فکر و همراهی.',
    teamLabel: 'آدم‌های پشت محصول',
    teamTitle: ['پنج نگاه،', 'یک هدف مشترک.'],
    teamIntro: 'طراحی، نرم‌افزار و زیرساخت، پشت یک میز. با آدم‌هایی آشنا شو که همراهت می‌سازند.',
    profile: 'آشنایی با',
    skills: 'تخصص‌های منتخب',
    linkedin: 'پروفایل حرفه‌ای ↗',
    expLabel: 'تجربه‌ای که همراه می‌آوریم',
    expTitle: ['کار واقعی،', 'مسئولیت واقعی.'],
    expIntro:
      'اعضای ما در ساخت محصول و توسعه تیم‌های بانکی، صنعتی، سلامت و خدمات روزمره نقش داشته‌اند.',
    expNote: 'سوابق کاری و پروژه‌های اعضای تیم؛ برای دیدن نوع همکاری، هر مجموعه را انتخاب کن.',
    source: 'تجربه عضو تیم',
    stackLabel: 'ابزار مناسب برای هر مسئله',
    stackTitle: ['ابزارهای متنوع،', 'انتخاب سنجیده.'],
    stackIntro:
      'اول مسئله را می‌فهمیم، بعد ابزار را انتخاب می‌کنیم. این‌ها بخشی از فناوری‌های مسیر حرفه‌ای ما هستند.',
    people: 'تجربه در تیم',
    contactLabel: 'هر محصول خوبی از جایی شروع می‌شود',
    contactTitle: ['چی تو', 'ذهنته؟'],
    contactIntro:
      'یک ایده تازه، بهترکردن محصول فعلی، یا مسئله‌ای که هنوز داری کشفش می‌کنی. از همان‌جا شروع کنیم.',
    needs: ['محصول تازه', 'تجربه بهتر', 'زیرساخت مطمئن', 'هوش مصنوعی و اتوماسیون'],
    placeholder: 'چند خط درباره چیزی که دوست داری بسازی…',
    download: 'ذخیره شرح پروژه',
    downloaded: 'شرح پروژه ذخیره شد. چیزی ارسال نشده است.',
    contactNote:
      'شرح پروژه را روی دستگاه ذخیره کن یا مستقیم برایمان ایمیل بزن؛ هر پیام را می‌خوانیم.',
    emailUs: 'ایمیل به ما',
    pause: 'توقف روایت',
    play: 'پخش روایت',
    prev: 'بخش قبلی',
    next: 'بخش بعدی',
    skip: 'بریم سراغ ایده تو',
    replay: 'دوباره ببین',
    footer: 'با فکر، کنار هم.',
    preview: 'پیش‌نمایش طراحی',
    choose: 'تنظیم تجربه',
    chaptersLabel: 'بخش‌های روایت',
  },
  ar: {
    brand: 'دانور',
    descriptor: 'تصميم المنتجات وهندسة البرمجيات',
    chapters: ['أهلاً', 'فريقنا', 'خبراتنا', 'أدواتنا', 'فكرتك'],
    settings: 'تجربة تناسبك',
    settingsHint: 'اختر ما يريحك. تُحفظ تفضيلاتك في هذا المتصفح.',
    close: 'إغلاق',
    theme: 'المظهر',
    modes: ['النظام', 'فاتح', 'داكن'],
    palette: 'ألوان على ذوقك',
    paletteNames: ['لوزي', 'وردي هادئ', 'طيني', 'رملي', 'مريمي', 'أزرق ضبابي'],
    keep: 'احتفظ بهذا المظهر',
    vary: 'مظهر جديد في الزيارة القادمة',
    reduced: 'حركة أقل',
    audio: 'اقرأ هذا الفصل',
    audioMissing: 'لا يتوفر صوت لهذه اللغة على الجهاز.',
    language: 'اللغة',
    hello: 'أهلاً، نحن دانور.',
    title: ['أفكار جميلة.', 'وفريق يهتم.'],
    intro: 'خمسة متخصصين يهتمون بما تبنيه. من أول فكرة إلى يوم إطلاق منتجك.',
    meet: 'تعرّف علينا',
    explore: 'اكتشف خبراتنا',
    small: 'نفكّر في المنتج. نتقن الهندسة. ونتواصل ببساطة.',
    note: 'فكرة مدروسة. وعمل متقن.',
    paper: ['نفهم الفكرة', 'نصمّم التجربة', 'نبني بثقة'],
    paperLabel: 'كيف نبني معاً',
    paperFooter: 'خطوة مدروسة في كل مرة.',
    teamLabel: 'الأشخاص وراء المنتج',
    teamTitle: ['خمس وجهات نظر.', 'هدف واحد.'],
    teamIntro: 'التصميم والبرمجيات والبنية التحتية على طاولة واحدة. تعرّف على فريق العمل.',
    profile: 'تعرّف على',
    skills: 'تخصصات مختارة',
    linkedin: 'الملف المهني ↗',
    expLabel: 'خبرات نحملها معنا',
    expTitle: ['عمل حقيقي.', 'مسؤولية حقيقية.'],
    expIntro: 'ساهم أعضاء فريقنا في منتجات وفرق في المصارف والصناعة والصحة والخدمات اليومية.',
    expNote: 'خبرات مهنية ومشاريع لأعضاء الفريق. اختر المؤسسة لمعرفة طبيعة العلاقة.',
    source: 'خبرة عضو الفريق',
    stackLabel: 'الأداة المناسبة للمهمة',
    stackTitle: ['أدوات متعددة.', 'اختيار مدروس.'],
    stackIntro:
      'نختار التقنية بناءً على المشكلة. هذه بعض الأدوات التي عملنا بها خلال مسيرتنا المهنية.',
    people: 'الخبرة في الفريق',
    contactLabel: 'كل منتج جيد يبدأ بفكرة',
    contactTitle: ['ما الذي', 'تفكّر فيه؟'],
    contactIntro: 'فكرة جديدة، منتج تريد تطويره، أو تحدٍ ما زلت تستكشفه. لنبدأ من حيث أنت.',
    needs: ['منتج جديد', 'تجربة أفضل', 'بنية موثوقة', 'الذكاء الاصطناعي والأتمتة'],
    placeholder: 'بضع كلمات حول ما تريد بناءه…',
    download: 'احفظ موجز المشروع',
    downloaded: 'حُفظ الموجز. لم يتم إرسال أي شيء.',
    contactNote: 'احفظ الموجز محلياً أو راسلنا مباشرة عبر البريد؛ نقرأ كل رسالة.',
    emailUs: 'راسلنا',
    pause: 'إيقاف القصة',
    play: 'تشغيل القصة',
    prev: 'الفصل السابق',
    next: 'الفصل التالي',
    skip: 'إلى فكرتك',
    replay: 'شاهد مجدداً',
    footer: 'نصنع بعناية، معاً.',
    preview: 'معاينة التصميم',
    choose: 'تخصيص التجربة',
    chaptersLabel: 'فصول القصة',
  },
};
